### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by JessieLOliver** [SciStarter-Team/SciStarter-Bugs#23]
When clicking the thumbnail for "Victoria's bushfire emergency: Biodiversity response and recovery (https://scistarter.org/exchange/35/9303/project.html) an "Internal server error" occurred.

**Comment by SciStarter** [comment]
Note: The failing URL is https://scistarter.org/exchange/35/1938/project.html while the Victoria's Bushfire page linked above works fine, though it did come up in a different issue we discussed.

**Comment by SciStarter** [comment]
Fixed. There is a value in one of this project's fields which is quite odd, but coercing that field into a more reasonable shape allows the page to be properly displayed even with the strange value.

Side note: This project is indeed tagged with "bats", which is why it showed up on the search which brought this error to light in the first place.

**Comment by ElMounRo** [comment]
Tested and working.
